# Generated by Django 5.1.3 on 2024-12-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandform',
            name='bname',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
