<<<<<<< HEAD
# Generated by Django 5.1 on 2024-12-18 06:50
=======
# Generated by Django 5.1 on 2024-12-18 06:05
>>>>>>> 4ffc9292d0922e5c37b948ac50fc432c183261fd

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0004_brandform_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandform',
            name='bid',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
