# Generated by Django 3.2.25 on 2025-01-20 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posmaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pos_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='posmaster.posmaster')),
            ],
        ),
    ]
