# Generated by Django 5.1.4 on 2024-12-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=255)),
                ('hsncode', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('tax', models.CharField(max_length=255)),
                ('punit', models.CharField(max_length=255)),
                ('aunit', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_product',
            },
        ),
    ]
