# Generated by Django 5.1.4 on 2024-12-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='cfactor',
            field=models.CharField(default='1', max_length=255),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='price',
            field=models.CharField(default='1', max_length=255),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='taxtype',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
