# Generated by Django 5.1.4 on 2024-12-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_productmodel_cfactor_productmodel_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='pid',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
