# Generated by Django 5.1 on 2024-12-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_productmodel_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='cfactor',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='taxtype',
            field=models.CharField(default='standard', max_length=255),
        ),
    ]
