# Generated by Django 3.2.25 on 2024-12-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_alter_productmodel_cfactor_alter_productmodel_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='cfactor',
            field=models.CharField(default='1', max_length=255),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.CharField(default='1', max_length=255),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='tax',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='taxtype',
            field=models.CharField(max_length=255),
        ),
    ]
