# Generated by Django 3.2.25 on 2024-12-31 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membername', models.CharField(max_length=255)),
                ('mobno', models.CharField(max_length=255)),
                ('emobno', models.CharField(max_length=255)),
                ('emaileadd', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=255)),
                ('datejoining', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('lastexperience', models.CharField(max_length=255)),
                ('lastworkcom', models.CharField(max_length=255)),
                ('lastcomsalary', models.CharField(max_length=255)),
                ('adharnum', models.CharField(max_length=255)),
                ('pannum', models.CharField(max_length=255)),
                ('userupi', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('adharimg', models.FileField(max_length=255, null=True, upload_to='Employee/')),
                ('panimg', models.FileField(max_length=255, null=True, upload_to='Employee/')),
                ('proimg', models.FileField(max_length=255, null=True, upload_to='Employee/')),
                ('qrimg', models.FileField(max_length=255, null=True, upload_to='Employee/')),
            ],
            options={
                'db_table': 'tbl_Employee',
            },
        ),
    ]
