# Generated by Django 5.1 on 2024-12-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=255)),
                ('c_img', models.FileField(max_length=255, null=True, upload_to='category/')),
                ('B_img', models.FileField(max_length=255, null=True, upload_to='category/')),
            ],
            options={
                'db_table': 'tbl_category',
            },
        ),
    ]
