<<<<<<< HEAD
# Generated by Django 5.1.3 on 2024-12-06 04:07
=======
# Generated by Django 5.1 on 2024-12-06 04:11
>>>>>>> 6fee515ba81325fca3b87c913d874e02ddac568e

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='c_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
