# Generated by Django 5.1 on 2024-12-19 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_category_c_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='c_id',
        ),
    ]
