# Generated by Django 3.2.25 on 2024-12-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_remove_category_c_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cid',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
