# Generated by Django 3.2.25 on 2024-12-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RewarsPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minrange', models.CharField(max_length=255)),
                ('maxrange', models.CharField(max_length=15)),
                ('points', models.EmailField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_rewards',
            },
        ),
    ]
