# Generated by Django 3.2.25 on 2024-12-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reward', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewarspoints',
            name='maxrange',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rewarspoints',
            name='minrange',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rewarspoints',
            name='points',
            field=models.IntegerField(),
        ),
    ]
